### ISSUE TITLE
LaTeX commands in TITLE field (bibtex files) are not preserved when importing

### ISSUE THREAD

**Issue by torralbofco** [sourcethemes/academic-admin#45]
After importing a bibtex file with the following entry:

```bibtex
@article {MR3750218,
    AUTHOR = {Alarc\'{o}n, Antonio and Forstneri\v{c}, Franc},
     TITLE = {Complete densely embedded complex lines in {$\Bbb C^2$}},
   JOURNAL = {Proc. Amer. Math. Soc.},
  FJOURNAL = {Proceedings of the American Mathematical Society},
    VOLUME = {146},
      YEAR = {2018},
    NUMBER = {3},
     PAGES = {1059--1067},
      ISSN = {0002-9939},
   MRCLASS = {32H02 (32E10 32M17 53C42)},
  MRNUMBER = {3750218},
MRREVIEWER = {Yu Kawakami},
       DOI = {10.1090/proc/13873},
       URL = {https://doi.org/10.1090/proc/13873},
}
```

I obtained the following markdown file for the publication entry

```yaml
---
title: "Complete densely embedded complex lines in $Bbb C^2$"
date: 2018-01-01
publishDate: 2019-08-23T19:28:30.647940Z
authors: ["Antonio Alarcón", "Franc Forstnerič"]
publication_types: ["2"]
abstract: ""
featured: false
publication: "*Proc. Amer. Math. Soc.*"
url_pdf: "https://doi.org/10.1090/proc/13873"
doi: "10.1090/proc/13873"
---
```

Observe how the characters in the authors name are correctly transformed but **the backslash character of the LaTeX command \Bbb (for blackboard letter) is missing in the title**. This produce a bad formater title. 

Compare the two images below. The first one is with "$Bbb C^2$" while the second one is "$\\Bbb C^2$" (which is the correct one).

<img width="781" alt="Captura de pantalla 2019-08-23 a las 21 36 26" src="https://user-images.githubusercontent.com/2292446/63619185-372b8c80-c5ee-11e9-9274-4c89c370cf79.png">

<img width="779" alt="Captura de pantalla 2019-08-23 a las 21 37 18" src="https://user-images.githubusercontent.com/2292446/63619188-37c42300-c5ee-11e9-99ea-7685b0167849.png">

 The character "\\" inside $$ in the title should be doubled instead of removed. See for instance the warning at the end of the [Manually managing content](https://sourcethemes.com/academic/docs/managing-content/#manually) in the academic documentation.
